add_executable(test_hls_filter test_hls_filter.c ../lib/hls_filter.c)
target_include_directories(test_hls_filter PRIVATE ../lib)
add_test(NAME hls_filter COMMAND test_hls_filter)
add_test(NAME hls_options COMMAND uxplay -hls-codecs h264:h265 -hls-max-resolution 1920x1080 -v)
add_test(NAME hls_options_reset COMMAND uxplay -hls-codecs all -hls-max-resolution 0 -v)
add_test(NAME hls_invalid_codec COMMAND uxplay -hls-codecs vp7 -v)
set_tests_properties(hls_invalid_codec PROPERTIES WILL_FAIL TRUE)
add_test(NAME hls_invalid_resolution COMMAND uxplay -hls-max-resolution 1920x1080junk -v)
set_tests_properties(hls_invalid_resolution PROPERTIES WILL_FAIL TRUE)
add_test(NAME hls_missing_codec COMMAND uxplay -hls-codecs)
set_tests_properties(hls_missing_codec PROPERTIES WILL_FAIL TRUE)
add_test(NAME hls_missing_resolution COMMAND uxplay -hls-max-resolution)
set_tests_properties(hls_missing_resolution PROPERTIES WILL_FAIL TRUE)
